language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: QXVltISq6PcYyj0/ejeWVKyivCQ1hWpa1FwmPzFI/EZtDyLGOghRfE5bcOkcsRw/Xf271c1+/hFtC/etIaspv/MjHygqqR8IWuD/cDRUzSxvczJ00sEcf+KNf+fmVKKxr4av96h/QSoSMnxf/LKueMsae+pJyaE3niHJz9Denf6hrXB/Hm6YPzAbOvzEHnQY4gBKOL7ryC0cJk7JUEFoczSywFL6ULJjMcWye2YRRPOZUO3sXEL9cTeYEZT3U3yHCRG+Yjkbqrv/BSJF46JsyeQccpmWSIxlBULvYIx+wQf/teiMn1xNQ4PlrDxhYnjpxI+WpGgrYERVIlDJFoX/gxuDFCosHQzJcDwQ8icg+fcn8UGe+b8gEqteF6DnB0OnIsb9HgOuK/nhJZjM0F+Py4BRF5jjvfVw37OXwOV42cB41c0CpreYHxxlNVL/2LwkyD4vkxwl2kEs9JTCD43e7Wb//Tk5HjEjGOKjWJucWrb/t/blCQO3l+8YOqAT5HQ+uNquut3PInFDnImUB8iMGSjUPIYmkELGbuLnJRPrkA0rzVxr1oohh3cLFwWbVTK6cc3l+2C1nR6mGujgCh+BgFSbZhcLqwQR187bIS8+XwafgJ0KQcEhrpVGkfvdQvSH3TZ3k+rrR44Y7fLNQhV9Lx5mYWf1OyayhcuS3aPE6nw=
  app: brain404-backend
  on:
    repo: Brain404/maze-09-2016
